"""
drone_env/core/tasks.py
Mission configurations for Drone Delivery missions.
"""

TASK_CONFIG = {
    "graders:grade_easy": {
        "width": 10,
        "height": 10,
        "n_buildings": 4,
        "n_trees": 4,
        "n_obstacles": 3,
        "n_deliveries": 1,
        "max_steps": 60,
        "battery_max": 60,
        "battery_cost": 1,
        "r_delivery": 0.95,
        "r_step": 0.10,
        "r_wait": 0.10,
        "r_obstacle": 0.10,
        "r_building": 0.10,
        "r_tree": 0.10,
        "r_battery_dead": 0.10,
        "r_wall": 0.10,
        "r_blocked": 0.10,
    },
    "graders:grade_medium": {
        "width": 14,
        "height": 14,
        "n_buildings": 8,
        "n_trees": 6,
        "n_obstacles": 6,
        "n_deliveries": 3,
        "max_steps": 100,
        "battery_max": 100,
        "battery_cost": 1,
        "r_delivery": 0.90,
        "r_step": 0.15,
        "r_wait": 0.15,
        "r_obstacle": 0.15,
        "r_building": 0.15,
        "r_tree": 0.15,
        "r_battery_dead": 0.15,
        "r_wall": 0.15,
        "r_blocked": 0.15,
    },
    "graders:grade_hard": {
        "width": 18,
        "height": 18,
        "n_buildings": 12,
        "n_trees": 10,
        "n_obstacles": 10,
        "n_deliveries": 5,
        "max_steps": 160,
        "battery_max": 160,
        "battery_cost": 1,
        "r_delivery": 0.85,
        "r_step": 0.25,
        "r_wait": 0.25,
        "r_obstacle": 0.25,
        "r_building": 0.25,
        "r_tree": 0.25,
        "r_battery_dead": 0.25,
        "r_wall": 0.25,
        "r_blocked": 0.25,
    }
}
