"""
drone_env/core/tasks.py
Mission configurations for Drone Delivery missions.
"""

TASK_CONFIG = {
    "graders:grade_easy": {
        "width": 12,
        "height": 12,
        "n_drones": 2,
        "n_deliveries": 3,
        "n_buildings": 6,
        "n_trees": 5,
        "n_obstacles": 4,
        "max_steps": 100,
        "battery_max": 100,
        "battery_cost": 0.5,
        "r_delivery": 0.9,
        "r_pickup": 0.4,
        "r_step": 0.01,
        "r_wait": 0.01,
        "r_obstacle": 0.05,
        "r_building": 0.05,
        "r_tree": 0.05,
        "r_battery_dead": 0.01,
        "r_wall": 0.05,
        "r_blocked": 0.05,
    },
    "graders:grade_medium": {
        "width": 16,
        "height": 16,
        "n_drones": 3,
        "n_deliveries": 5,
        "n_buildings": 10,
        "n_trees": 8,
        "n_obstacles": 8,
        "max_steps": 150,
        "battery_max": 150,
        "battery_cost": 0.5,
        "r_delivery": 0.9,
        "r_pickup": 0.4,
        "r_step": 0.01,
        "r_wait": 0.01,
        "r_obstacle": 0.05,
        "r_building": 0.05,
        "r_tree": 0.05,
        "r_battery_dead": 0.01,
        "r_wall": 0.05,
        "r_blocked": 0.05,
    },
    "graders:grade_hard": {
        "width": 20,
        "height": 20,
        "n_drones": 4,
        "n_deliveries": 10,
        "n_buildings": 15,
        "n_trees": 12,
        "n_obstacles": 12,
        "max_steps": 250,
        "battery_max": 250,
        "battery_cost": 0.5,
        "r_delivery": 0.9,
        "r_pickup": 0.4,
        "r_step": 0.01,
        "r_wait": 0.01,
        "r_obstacle": 0.05,
        "r_building": 0.05,
        "r_tree": 0.05,
        "r_battery_dead": 0.01,
        "r_wall": 0.05,
        "r_blocked": 0.05,
    }
}
